### ISSUE TITLE
Need commas for the DAA value in CSV files, but this is unable to read them.

### ISSUE THREAD

**Issue by barkythephysicsdog** [transgen/Transgen#1]
When you batch generate, it requires a CSV file.  However, as a result, you can't upload the full correct name format (LAST,FIRST,M) that includes the commas.

**Comment by transgen** [comment]
You fixed this by adding escape characters.

**Comment by barkythephysicsdog2** [comment]
Can you tell me what it would be?  I'm not a computer science person so this is confusing.  I've tried almost everything I can think of, and research isn't helping me.  I'm generating the CSV files from Excel, which uses the solution of putting the string(?) in double quotes.  But when I try to batch generate it won't generate.  From what I'm reading, I guess Java doesn't recognize commas as meaning anything.  I even tried opening the CSV into Notepad and removing one set of commas, but that didn't work either.  Please help.

**Comment by transgen** [comment]
Added support.

You can now include like this: ,Joe\, Anderson\, M ,
Will read in Joe, Anderson as one field
